# Generated by Django 5.2.16 on 2026-09-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='`evt_xxx` tal como lo envía Stripe. Único: bloquea duplicados.', max_length=120, unique=True, verbose_name='ID del evento')),
                ('event_type', models.CharField(max_length=80, verbose_name='Tipo de evento')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibido el')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Relleno tras procesar el evento; vacío si falló.', null=True, verbose_name='Procesado el')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Objeto del evento completo tal como lo envió Stripe.', verbose_name='Carga útil')),
                ('error', models.TextField(blank=True, default='', help_text='Mensaje de excepción si el procesamiento falló.', verbose_name='Error')),
            ],
            options={
                'verbose_name': 'Evento de Stripe',
                'verbose_name_plural': 'Eventos de Stripe',
                'ordering': ['-received_at'],
            },
        ),
    ]
