# Generated by Django 5.2.16 on 2026-08-09 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de pieza',
                'verbose_name_plural': 'Tipos de pieza',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tamaño',
                'verbose_name_plural': 'Tamaños',
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Técnica',
                'verbose_name_plural': 'Técnicas',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Temática',
                'verbose_name_plural': 'Temáticas',
            },
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='category',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='surface',
        ),
        migrations.AddField(
            model_name='artwork',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.discipline'),
        ),
        migrations.CreateModel(
            name='DisciplineTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.discipline')),
            ],
            options={
                'unique_together': {('discipline', 'language')},
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='formats',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.format'),
        ),
        migrations.CreateModel(
            name='FormatTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.format')),
            ],
            options={
                'unique_together': {('format', 'language')},
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='scales',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.scale'),
        ),
        migrations.CreateModel(
            name='ScaleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.scale')),
            ],
            options={
                'unique_together': {('scale', 'language')},
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.technique'),
        ),
        migrations.CreateModel(
            name='TechniqueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.technique')),
            ],
            options={
                'unique_together': {('technique', 'language')},
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.theme'),
        ),
        migrations.CreateModel(
            name='ThemeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.theme')),
            ],
            options={
                'unique_together': {('theme', 'language')},
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryTranslation',
        ),
        migrations.DeleteModel(
            name='Medium',
        ),
        migrations.DeleteModel(
            name='MediumTranslation',
        ),
        migrations.DeleteModel(
            name='Surface',
        ),
        migrations.DeleteModel(
            name='SurfaceTranslation',
        ),
    ]
