# Generated by Django 5.2.16 on 2026-08-09 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_location_artwork_is_highlighted_artwork_views_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artcurator',
            options={'verbose_name': 'Curador de arte', 'verbose_name_plural': 'Curadores de arte'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
        migrations.AlterModelOptions(
            name='artwork',
            options={'verbose_name': 'Obra de arte', 'verbose_name_plural': 'Obras de arte'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galería', 'verbose_name_plural': 'Galerías'},
        ),
        migrations.AlterField(
            model_name='artcurator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='artcurator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='artcurator',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='artcurator',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='artcurator',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='artcurator',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='artcurator',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='artcurator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='artcurator',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='artcuratortranslation',
            name='art_curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.artcurator', verbose_name='Curador de arte'),
        ),
        migrations.AlterField(
            model_name='artcuratortranslation',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='artcuratortranslation',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de nacimiento'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='death_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de fallecimiento'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='artworks.location', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='artistsociallink',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='artworks.artist', verbose_name='Artista'),
        ),
        migrations.AlterField(
            model_name='artistsociallink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='artistsociallink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='artistsociallink',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X (Twitter)'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('behance', 'Behance'), ('other', 'Otra')], max_length=20, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='artistsociallink',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='artistsociallink',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='artistsociallink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='artistsociallink',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='artisttranslation',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.artist', verbose_name='Artista'),
        ),
        migrations.AlterField(
            model_name='artisttranslation',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='artisttranslation',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='artworks.artist', verbose_name='Artista'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='dimensions',
            field=models.CharField(max_length=100, verbose_name='Dimensiones'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.discipline', verbose_name='Disciplinas'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='formats',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.format', verbose_name='Tipos de pieza'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='Destacada'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='price_mxn',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (MXN)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (USD)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='scales',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.scale', verbose_name='Tamaños'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendida'), ('reserved', 'Reservada'), ('on_loan', 'En préstamo'), ('not_available', 'No disponible')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.technique', verbose_name='Técnicas'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.theme', verbose_name='Temáticas'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visitas'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='artworkgallery',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_links', to='artworks.artwork', verbose_name='Obra de arte'),
        ),
        migrations.AlterField(
            model_name='artworkgallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='artworkgallery',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_links', to='artworks.gallery', verbose_name='Galería'),
        ),
        migrations.AlterField(
            model_name='artworkgallery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='artworkgallery',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='artworkgallery',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='artworkgallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='alt_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo (EN)'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='alt_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo (ES)'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artworks.artwork', verbose_name='Obra de arte'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='artworktranslation',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.artwork', verbose_name='Obra de arte'),
        ),
        migrations.AlterField(
            model_name='artworktranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='artworktranslation',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='artworktranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='disciplinetranslation',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.discipline', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplinetranslation',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='disciplinetranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='format',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='format',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='format',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='format',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='format',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='formattranslation',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.format', verbose_name='Tipo de pieza'),
        ),
        migrations.AlterField(
            model_name='formattranslation',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='formattranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_galleries', to='artworks.artcurator', verbose_name='Curador'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logotipo'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='gallerytranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='gallerytranslation',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.gallery', verbose_name='Galería'),
        ),
        migrations.AlterField(
            model_name='gallerytranslation',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='gallerytranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='location',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='locationtranslation',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='locationtranslation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.location', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='locationtranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='scaletranslation',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='scaletranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='scaletranslation',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.scale', verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='techniquetranslation',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='techniquetranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='techniquetranslation',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.technique', verbose_name='Técnica'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='themetranslation',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='themetranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='themetranslation',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artworks.theme', verbose_name='Temática'),
        ),
    ]
