# Generated by Django 5.2.16 on 2026-08-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_alter_artcurator_options_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcurator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='artistsociallink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='artworkgallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='format',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
    ]
