# Generated by Django 5.2.15 on 2026-08-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_alter_artcurator_slug_alter_artist_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistsociallink',
            options={},
        ),
        migrations.RemoveField(
            model_name='artcurator',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='artistsociallink',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='format',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='location',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='sort_order',
        ),
    ]
