# Generated by Django 5.2.15 on 2026-08-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_alter_artistsociallink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Marca la galería principal de la colección. Solo puede existir una única galería principal en todo el backend.', verbose_name='Galería principal'),
        ),
        migrations.AddConstraint(
            model_name='gallery',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('is_primary',), name='unique_primary_gallery'),
        ),
    ]
