# Generated by Django 5.2.15 on 2026-08-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_gallery_is_primary_gallery_unique_primary_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Marca la galería principal de la colección. Solo puede existir una única galería principal en todo el sistema.', verbose_name='Galería principal'),
        ),
    ]
