# Generated by Django 5.2.17 on 2026-09-17 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0010_artist_email_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('paid_pending_data', 'Pagado (pendiente de datos)'), ('data_complete', 'Datos completos'), ('shipped', 'Enviada'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], default='pending_payment', max_length=20, verbose_name='Estado')),
                ('currency', models.CharField(choices=[('mxn', 'MXN'), ('usd', 'USD')], help_text='Moneda elegida por el comprador al iniciar la compra.', max_length=3, verbose_name='Moneda')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto cobrado (foto del precio al momento de la compra).', max_digits=10, verbose_name='Monto')),
                ('stripe_checkout_session_id', models.CharField(blank=True, help_text='Identificador de la Checkout Session en Stripe.', max_length=200, verbose_name='ID de sesión Stripe')),
                ('checkout_url', models.URLField(blank=True, help_text='URL de Checkout enviada al comprador.', max_length=500, verbose_name='URL de pago')),
                ('session_expires_at', models.DateTimeField(blank=True, help_text='Expiración de la sesión de pago (reserva válida hasta entonces).', null=True, verbose_name='Vence la sesión')),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='PaymentIntent confirmado por el webhook.', max_length=200, verbose_name='ID de pago Stripe')),
                ('buyer_email', models.EmailField(help_text='Dueño de la reserva; Checkout lo bloquea como customer_email.', max_length=254, verbose_name='Correo del comprador')),
                ('buyer_name', models.CharField(blank=True, help_text='Nombre capturado por Stripe al pagar.', max_length=200, verbose_name='Nombre del comprador')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagado el')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado el')),
                ('receiver_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del destinatario')),
                ('receiver_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono del destinatario')),
                ('country', models.CharField(blank=True, default='México', max_length=100, verbose_name='País')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('neighborhood', models.CharField(blank=True, max_length=150, verbose_name='Colonia')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Calle')),
                ('exterior_number', models.CharField(blank=True, max_length=30, verbose_name='Número exterior')),
                ('interior_number', models.CharField(blank=True, help_text='Opcional: departamento, lote o interior.', max_length=30, verbose_name='Número interior')),
                ('between_street_1', models.CharField(blank=True, help_text='Opcional: referencia de ubicación mexicana.', max_length=200, verbose_name='Entre calle 1')),
                ('between_street_2', models.CharField(blank=True, help_text='Opcional: segunda referencia de ubicación.', max_length=200, verbose_name='Entre calle 2')),
                ('reference', models.TextField(blank=True, help_text='Opcional: cómo llegar o señas del domicilio.', verbose_name='Referencias')),
                ('delivery_notes', models.TextField(blank=True, help_text='Opcional: instrucciones adicionales para el envío.', verbose_name='Notas de entrega')),
                ('artwork', models.ForeignKey(help_text='Obra única vendida en esta orden (protegida contra borrado).', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='artworks.artwork', verbose_name='Obra de arte')),
            ],
            options={
                'verbose_name': 'Pedido de obra',
                'verbose_name_plural': 'Pedidos de obras',
                'ordering': ['-created_at'],
            },
        ),
    ]
