# Generated by Django 5.2.17 on 2026-09-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0011_artworkorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistsociallink',
            options={'verbose_name': 'Red social del artista', 'verbose_name_plural': 'Redes sociales del artista'},
        ),
        migrations.CreateModel(
            name='ArtCuratorSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X (Twitter)'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('behance', 'Behance'), ('other', 'Otra')], max_length=20, verbose_name='Plataforma')),
                ('url', models.URLField(verbose_name='URL')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='artworks.artcurator', verbose_name='Curador de arte')),
            ],
            options={
                'verbose_name': 'Red social del curador',
                'verbose_name_plural': 'Redes sociales del curador',
            },
        ),
    ]
