# Generated by Django 5.2.17 on 2026-09-26 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_alter_artistsociallink_options_artcuratorsociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='commission',
            field=models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de la venta de obras que corresponde al artista (0 a 100). El porcentaje restante corresponde a Enredarte.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comisión del artista (%)'),
        ),
    ]
