# Generated by Django 5.2.16 on 2026-10-01 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0013_artist_commission'),
        ('subscriptions', '0007_delete_stripeevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('occurred_on', models.DateField(db_index=True, help_text='Fecha del movimiento; determina el mes al que pertenece.', verbose_name='Fecha')),
                ('kind', models.CharField(choices=[('artwork_sale', 'Venta de obra'), ('artist_commission', 'Comisión de artista'), ('subscription_payment', 'Pago de suscripción')], help_text='Naturaleza del movimiento: venta, comisión o pago de suscripción.', max_length=32, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto con signo: positivo para ingresos, negativo para gastos (comisiones).', max_digits=10, verbose_name='Monto')),
                ('currency', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], help_text='Moneda del movimiento. Los totales se agrupan por moneda.', max_length=3, verbose_name='Moneda')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('stripe', 'En línea')], help_text='En línea (Stripe) o efectivo. Vacío para movimientos sin método.', max_length=10, null=True, verbose_name='Método de pago')),
                ('reference', models.CharField(blank=True, help_text='Clave del evento de origen; evita registrar el mismo movimiento dos veces.', max_length=200, verbose_name='Referencia')),
                ('note', models.CharField(blank=True, help_text='Descripción breve del movimiento.', max_length=255, verbose_name='Nota')),
                ('reconciled', models.BooleanField(default=False, help_text='Marca manual: el movimiento ya fue validado (o la comisión ya se pagó al artista).', verbose_name='Conciliado')),
                ('artist', models.ForeignKey(blank=True, help_text='Artista relacionado (venta, comisión o suscripción).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='artworks.artist', verbose_name='Artista')),
                ('order', models.ForeignKey(blank=True, help_text='Pedido que originó el movimiento, cuando aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='artworks.artworkorder', verbose_name='Pedido de obra')),
                ('subscription', models.ForeignKey(blank=True, help_text='Suscripción que originó el movimiento, cuando aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='subscriptions.artistsubscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-occurred_on', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('kind', 'reference'), name='unique_finance_kind_reference')],
            },
        ),
    ]
