# Generated by Django 5.2.16 on 2026-08-15 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(help_text='Nombre descriptivo de la imagen', max_length=255, verbose_name='Nombre')),
                ('image', models.ImageField(help_text='Archivo de imagen para subir', upload_to='blog/images', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Imagen de blog',
                'verbose_name_plural': 'Imágenes de blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Orden')),
                ('banner_image_url', models.CharField(blank=True, help_text='URL o enlace a la imagen del banner', max_length=500, null=True, verbose_name='URL del banner')),
                ('author', models.CharField(default='Equipo Enredarte', help_text='Nombre del autor o equipo redactor', max_length=200, verbose_name='Autor')),
                ('published_at', models.DateTimeField(blank=True, help_text='Fecha y hora de publicación pública', null=True, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Entrada de blog',
                'verbose_name_plural': 'Entradas de blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5, verbose_name='Idioma')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(help_text='Resumen o extracto de la entrada para listas y SEO', verbose_name='Descripción corta')),
                ('keywords', models.CharField(blank=True, help_text='Palabras clave separadas por comas', max_length=255, verbose_name='Palabras clave')),
                ('content', models.TextField(help_text='Cuerpo completo del artículo', verbose_name='Contenido')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.post', verbose_name='Entrada de blog')),
            ],
            options={
                'verbose_name': 'Traducción de entrada',
                'verbose_name_plural': 'Traducciones de entradas',
                'unique_together': {('post', 'language')},
            },
        ),
    ]
