# Generated by Django 5.2.16 on 2026-08-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banner_image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Archivo de imagen de banner para la entrada', null=True, upload_to='blog/banners', verbose_name='Imagen de banner'),
        ),
    ]
