# Generated by Django 5.2.16 on 2026-08-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_banner_image_url_post_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sort_order',
        ),
    ]
