# Generated by Django 5.2.16 on 2026-08-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_banner_image_url_post_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Orden de la entrada dentro del listado', verbose_name='Orden'),
        ),
    ]
