# Generated by Django 5.2.16 on 2026-08-26 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_sort_order'),
        ('blog', '0003_remove_post_sort_order'),
    ]

    operations = [
    ]
