# Generated by Django 5.2.16 on 2026-08-21 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0009_alter_gallery_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Membresía Enredarte', help_text='Nombre mostrado en el admin. Solo informativo.', max_length=100, verbose_name='Nombre del plan')),
                ('stripe_price_id', models.CharField(blank=True, default='', help_text='Pega el `price_xxx` del producto creado en el Dashboard de Stripe.', max_length=100, verbose_name='ID de precio en Stripe')),
                ('currency', models.CharField(default='MXN', help_text='Código ISO 4217 de tres letras, p. ej. MXN.', max_length=3, verbose_name='Moneda (ISO 4217)')),
                ('grace_period_days', models.PositiveIntegerField(default=3, help_text='Días que un artista con pago fallido sigue visible en el sitio público.', verbose_name='Período de gracia (días)')),
                ('is_active_for_new_signups', models.BooleanField(default=True, help_text='Desactiva para pausar la generación de nuevos links de pago.', verbose_name='Aceptar nuevas suscripciones')),
            ],
            options={
                'verbose_name': 'Plan de suscripción',
                'verbose_name_plural': 'Planes de suscripción',
            },
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='`evt_xxx` tal como lo envía Stripe. Único: bloquea duplicados.', max_length=120, unique=True, verbose_name='ID del evento')),
                ('event_type', models.CharField(max_length=80, verbose_name='Tipo de evento')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibido el')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Relleno tras procesar el evento; vacío si falló.', null=True, verbose_name='Procesado el')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Objeto del evento completo tal como lo envió Stripe.', verbose_name='Carga útil')),
                ('error', models.TextField(blank=True, default='', help_text='Mensaje de excepción si el procesamiento falló.', verbose_name='Error')),
            ],
            options={
                'verbose_name': 'Evento de Stripe',
                'verbose_name_plural': 'Eventos de Stripe',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('active', 'Activa'), ('past_due', 'Pago fallido (en gracia)'), ('canceling', 'Cancelada, vigente hasta fin de período'), ('canceled', 'Cancelada definitivamente')], default='pending', max_length=20, verbose_name='Estado')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Identificador `cus_xxx` asignado al generar el primer link de pago.', max_length=100, null=True, unique=True, verbose_name='ID de cliente en Stripe')),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Identificador `sub_xxx` asignado tras el primer cobro.', max_length=100, null=True, unique=True, verbose_name='ID de suscripción en Stripe')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del cliente')),
                ('current_period_end', models.DateTimeField(blank=True, help_text='Fecha en que termina el período ya pagado (según Stripe).', null=True, verbose_name='Fin del período actual')),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Verdadero cuando el artista pidió cancelar y sigue visible hasta el fin del período.', verbose_name='Cancelar al fin del período')),
                ('signup_url', models.URLField(blank=True, default='', help_text='URL de la sesión de Checkout compartida con el artista.', max_length=2000, verbose_name='Link de pago')),
                ('signup_url_expires_at', models.DateTimeField(blank=True, help_text='Momento en que Stripe invalida la URL de Checkout.', null=True, verbose_name='El link de pago expira')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Actualizado por webhooks o por la acción manual «Sincronizar desde Stripe».', null=True, verbose_name='Última sincronización con Stripe')),
                ('raw_state', models.JSONField(blank=True, default=dict, help_text='Último objeto de Stripe procesado, para depuración.', verbose_name='Estado crudo de Stripe')),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='artworks.artist', verbose_name='Artista')),
            ],
            options={
                'verbose_name': 'Suscripción de artista',
                'verbose_name_plural': 'Suscripciones de artistas',
            },
        ),
    ]
