# Generated by Django 5.2.15 on 2026-08-26 23:02

import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_backfill_billingplan_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, default=subscriptions.models.default_stripe_price_id, help_text='Pega el `price_xxx` del producto creado en el Dashboard de Stripe.', max_length=100, verbose_name='ID de precio en Stripe'),
        ),
    ]
