# Generated by Django 5.2.16 on 2026-09-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_admin_editable_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistsubscription',
            name='payment_method',
            field=models.CharField(choices=[('online', 'En línea'), ('cash', 'Efectivo')], default='online', help_text='En línea: la suscripción se gestiona en Stripe. En efectivo: el control es manual desde el admin, sin Stripe.', max_length=10, verbose_name='Método de pago'),
        ),
    ]
