# Generated by Django 5.2.16 on 2026-09-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_artistsubscription_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistsubscription',
            name='cash_last_paid_at',
            field=models.DateField(blank=True, help_text='Fecha del último pago en efectivo confirmado. Vacío si nunca se confirmó un pago.', null=True, verbose_name='Último pago en efectivo'),
        ),
    ]
