# Generated by Django 5.2.16 on 2026-09-25 21:56
# Extended: copy StripeEvent rows to core before deleting the old model.

from django.db import migrations


def copy_stripe_events(apps, schema_editor):
    """Move every row to the new `core.StripeEvent` table, asserting no loss."""
    OldStripeEvent = apps.get_model("subscriptions", "StripeEvent")
    NewStripeEvent = apps.get_model("core", "StripeEvent")

    rows = list(OldStripeEvent.objects.all())
    if rows:
        NewStripeEvent.objects.bulk_create(
            [
                NewStripeEvent(
                    id=row.id,
                    event_id=row.event_id,
                    event_type=row.event_type,
                    received_at=row.received_at,
                    processed_at=row.processed_at,
                    payload=row.payload,
                    error=row.error,
                )
                for row in rows
            ],
            ignore_conflicts=True,
        )
    old_count = OldStripeEvent.objects.count()
    new_count = NewStripeEvent.objects.count()
    if new_count < old_count:
        raise RuntimeError(
            f"StripeEvent migration lost rows: old={old_count} new={new_count}"
        )


def restore_stripe_events(apps, schema_editor):
    """Reverse: copy rows back so a rollback never drops audit history."""
    OldStripeEvent = apps.get_model("subscriptions", "StripeEvent")
    NewStripeEvent = apps.get_model("core", "StripeEvent")

    rows = list(NewStripeEvent.objects.all())
    if rows:
        OldStripeEvent.objects.bulk_create(
            [
                OldStripeEvent(
                    id=row.id,
                    event_id=row.event_id,
                    event_type=row.event_type,
                    received_at=row.received_at,
                    processed_at=row.processed_at,
                    payload=row.payload,
                    error=row.error,
                )
                for row in rows
            ],
            ignore_conflicts=True,
        )
    if OldStripeEvent.objects.count() < NewStripeEvent.objects.count():
        raise RuntimeError(
            "Refusing to reverse StripeEvent move: rows would be lost from "
            "core.StripeEvent."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("subscriptions", "0006_artistsubscription_cash_last_paid_at"),
    ]

    operations = [
        migrations.RunPython(copy_stripe_events, restore_stripe_events),
        migrations.DeleteModel(
            name="StripeEvent",
        ),
    ]
